Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.hostname = "app-1"

  config.vm.network "private_network", ip: "192.168.56.3"

  config.vbguest.auto_update = false
  config.vm.network "forwarded_port", guest: 8080, host: 8080
end
