Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.hostname = "control-node"

  config.vm.network "private_network", ip: "192.168.56.2"

  config.vbguest.auto_update = false

  config.vm.synced_folder ".", "/vagrant/", type: "nfs"

  config.vm.provision "shell", path: "provision.sh"
end