Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.hostname = "db-1"

  config.vm.network "private_network", ip: "192.168.56.4"

  config.vbguest.auto_update = false
  config.vm.network "forwarded_port", guest: 3306, host: 3306
end
